[API]
  ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  Timeout = "60s"
[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/1235", "/ip6/::/tcp/1235"]
  AnnounceAddresses = []
[Pubsub]
  RemoteTracer = ""

[ActorEvent]
EnableRealTimeFilterAPI = true
EnableHistoricFilterAPI = true
ActorEventDatabasePath = "/home/lotus_user/.lotus/actor_event_db"
