#!/bin/bash

# make sure directory exists
mkdir -p /root/.lotus/keystore

# setup configuration
cp /root/config.toml /root/.lotus/config.toml
cp /etc/lotus-secret-vol/token /root/.lotus/token
cp /etc/lotus-secret-vol/privatekey /root/.lotus/keystore/MF2XI2BNNJ3XILLQOJUXMYLUMU

# turn on bash's job control
set -m

# Start the primary process and put it in the background
lotus daemon &

# the my_helper_process might need to know how to wait on the
# primary process to start before it does its work and returns
sleep 5

# Start the helper process
lotus sync wait >/dev/null

# bring the primary process back into the foreground
# and leave it there
fg %1
