#!/bin/sh

repeat() { while :; sleep 2; do $@ && return; done }

# setup configuration
cp /root/config.toml /root/.lotus/config.toml

while getopts sdc option
do
    case "${option}" in
        s) SYNC=true;;
        d) DAEMON=true;;
        c) CHAINWATCH=true;;
    esac
done
    
if [ "$DAEMON" == true ] ; then
    echo "Starting daemon"
    # Start the daemon process
    lotus daemon
fi

if [ "$SYNC" == true ] ; then
    echo "Starting sync wait"
    # Start the daemon process and put it in the background
    lotus daemon &
    # Run the sync process until it dies
    repeat lotus sync wait
fi

if [ "$CHAINWATCH" == true ] ; then
    echo "Starting chainwatch"
    # Start the daemon process and put it in the background
    lotus daemon &
    # Start the chainwatch process
    repeat chainwatch run
fi
