#!/bin/bash
#this script compares block on api.filscan and on nodes and checks if lotus sync status isn't error
#if api.filscan unavailable, it will compare with block on node which has higher block from several nodes.
set -e
if [[ $(curl -sk https://api.filscan.io/) ]]
  then
    global=$(curl -s --header "Content-Type: application/json" --request POST --data \
    '{"id": 1, "jsonrpc": "2.0", "method": "filscan.StatChainInfo"}' https://api.filscan.io:8700/rpc/v1 |\
     jq -r '.result.data.latest_height')
    local=$(curl -s localhost:1234/debug/metrics | grep ^lotus_chain_node_worker_height | awk '{print $2}')
    node=$(for i in {01..10}; do curl -s https://node.glif.io/space$i/lotus/debug/metrics | \
        grep ^lotus_chain_node_height | awk '{print $2}'; done)
    if [ -z "$global" ]
        then global=0
    fi
    count=$(echo $(( $(printf '%s\n'  $global $node | sort -nr | head -1)-250 )))

      if [[ $count -lt $local ]]
         then exit 0
      elif [[ -n $(lotus sync status | grep "Stage: error") ]]
         then exit 0
      else exit 1
      fi
  else
    local=$(curl -s localhost:1234/debug/metrics | grep ^lotus_chain_node_worker_height | awk '{print $2}')
    node=$(for i in {01..10}; do curl -s https://node.glif.io/space$i/lotus/debug/metrics | \
    grep ^lotus_chain_node_height | awk '{print $2}'; done | sort -nr | head -1)
    count=$(echo $(( $node-250 )))
      if [[ $count -lt $local ]]
        then exit 0
      else exit 1
      fi
fi