#!/usr/bin/env bash

. /etc/lotus/docker/bash-config

INFRA_VAR=$(env | grep INFRA_LOTUS_)

if [[ -z "$INFRA_VAR" ]] ; then
  echo "INFRA_LOTUS_DAEMON or INFRA_LOTUS_LITE or INFRA_LOTUS_GATEWAY aren't defined. Please setting up ..."
elif [ "$INFRA_LOTUS_GATEWAY" = true ]; then
  echo "Starting lotus daemon with gateway"
  # Start the daemon process with gateway
  lotus daemon &
  sleep 10 && lotus-gateway run
elif [ "$INFRA_LOTUS_DAEMON" = true ]; then
  echo "Starting daemon"
  # Start the daemon process
  lotus daemon
elif [ "$INFRA_LOTUS_LITE" = true ]; then
  if [[ -z "$FULLNODE_API_INFO" ]]; then
    echo "FULLNODE_API_INFO isn't defined in lotus lite mode. Please setting up ..."
  else
  # Start lotus daemon in lite mode
    lotus daemon --lite
  fi
elif [ "$INFRA_LOTUS_DAEMON" = false ]; then
  echo "DAEMON disabled."
fi

