#!/usr/bin/env bash

. /etc/lotus/docker/bash-config

if [[ -z "$INFRA_LOTUS_DAEMON" ]]
then
  echo "INFRA_LOTUS_DAEMON not defined. Please setting up ..."
elif [ "$INFRA_LOTUS_DAEMON" = true ]; then
  echo "Starting daemon"
  # Start the daemon process
  lotus daemon
elif [ "$INFRA_LOTUS_DAEMON" = false ]; then
  echo "DAEMON disabled."
fi