#!/bin/bash
# Perform a periodic export if export is enabled

if [[ "$LOTUS_EXPORT" -eq "true" ]]; then
  eudico chain export ${LOTUS_EXPORT_PATH}-new
  mv ${LOTUS_EXPORT_PATH}-new ${LOTUS_EXPORT_PATH}
fi
