#!/usr/bin/env bash

set -e

if [ $# -ne 1 ]
then
    echo "Provide the subnet ID as first argument for the script"
    exit 1
fi

SUBNETID=$1


echo "[*] Generate genesis for subnet deterministically"
if [[ "$SUBNETID" == "/root" ]]; then
    eudico genesis new --subnet-id=$SUBNETID --template=/etc/lotus/docker/genesis-test.json --out=/home/lotus_user/subnet.car
else
    eudico genesis new --subnet-id=$SUBNETID --template=/etc/lotus/docker/genesis.json --out=/home/lotus_user/subnet.car
fi

echo "[*] Starting daemon"
eudico mir daemon --genesis=/home/lotus_user/subnet.car --bootstrap=false

eudico wait-api --timeout=300s
sleep 5
eudico wallet import --as-default --format=json-lotus  /etc/lotus/docker/wallet.key
echo "[*] Initializing validator config and adding validator"
eudico mir validator config init

if [[ "$SUBNETID" == "/root" ]]; then
    validator_addr=`eudico mir validator config validator-addr | grep -vE '(/ip6/)' | grep -E '/ip4/127.0.0.1/tcp/1347'`
    eudico mir validator config add-validator $validator_addr
    echo "[*] Starting validator"
    eudico mir validator run --nosync
else
    echo "[*] Starting subnet validator"
    eudico mir validator run --membership=onchain --nosync --ipcagent-url=http://$IPC_AGENT_HOST:$IPC_AGENT_PORT/json_rpc
fi
