#!/usr/bin/env bash

set -e

if [ $# -ne 1 ]
then
    echo "Provide the subnet ID as first argument for the script"
    exit 1
fi

SUBNETID=$1


echo "[*] Generate genesis for subnet deterministically"
if [[ "$SUBNETID" == "/root" ]]; then
    eudico genesis new --subnet-id=$SUBNETID --template=/etc/lotus/docker/genesis-test.json --out=subnet.car
else
    eudico genesis new --subnet-id=$SUBNETID --template=/etc/lotus/docker/genesis.json --out=subnet.car
fi

echo "[*] Starting daemon"
eudico mir daemon --genesis=subnet.car --bootstrap=false
